on:
  push:
    branches: dev
    
name: 🚀 Deploy to DevSite on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        
    - name: 🔨 pkg installation and build
      run: |
          npm install 
          npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: ./mds-dev.mwerothewebmaker.com/
        local-dir: ./build/
        dangerous-clean-slate: true
